name             'usermanage'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures usermanage'
long_description 'Installs/Configures usermanage'
version          '0.1.0'
depends 'users', '~> 2'
